import icon from '../assets/course/icon.svg'
import image from '../assets/course/coursePic.svg'
import heart from '../assets/course/heart.svg'
import share from '../assets/course/share.svg'
import pic from '../assets/course/CourseImage.svg'
import eye from '../assets/course/eye.svg'
import lock from '../assets/course/Lock.svg'
import bell from '../assets/icon/bell.svg'
import cart from '../assets/icon/cart.svg'
import circle from '../assets/circle.svg'
import symbol from '../assets/symbol.svg'
import homeIcon from '../assets/icon/home.svg'
import homeGray from '../assets/icon/homeGray.svg'
import logo from '../assets/Logo.svg'
import plus from '../assets/chapter/plus.svg'
import rowImg from '../assets/chapter/rowImg.svg'
import up from '../assets/chapter/up.svg'
import edit from '../assets/chapter/edit.svg'
import down from '../assets/chapter/down.svg'
import del from '../assets/chapter/del.svg'
import video from '../assets/chapter/video.svg'
import warning from '../assets/chapter/warning.svg'
import play from '../assets/video/play.svg'
import videoImg from '../assets/video/videoPic.svg'
import quiz from '../assets/video/quiz.svg'

export {icon,image,heart,share,pic,eye,lock,bell,cart,circle,symbol,homeIcon,homeGray,logo,plus,rowImg,up,edit,down,del,video,warning,play,videoImg,quiz}