import Home from "./pages/Home/Home";
import Course from "./pages/Course/Course";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import HomeCard from "./components/HomeCard";
import CourseCard from "./components/CourseCard";
import Chapter from "./pages/Chapter/Chapter";
import OpenClose from "./components/OpenClose";
import Modal from "./components/Modal";
import Video from "./pages/Video/Video";
import ChapterCard from "./components/ChapterCard";
export {Home,Course,Navbar,Sidebar,HomeCard,CourseCard,Chapter,OpenClose,Modal,Video,ChapterCard};